vich_uploader:
    db_driver: orm

    mappings:
        trips:
            uri_prefix: /images/trips
            upload_destination: '%kernel.project_dir%/public/images/trips'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        documents:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/public/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
